name: Synapse Interface Cypress Integration Tests

on:
  push:
  pull_request:
    paths:
      - 'packages/explorer-ui/**'
      - '.github/workflows/ui-preview.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Run Cypress tests
        run: yarn cypress:run
