name: Explorer UI Deploy
on:
  push:
    branches: [master]
    paths:
      - 'packages/docs/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'packages/docs/**'

jobs:
  deploy-explorer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy nvmrc
        run: |
          rm -rf packages/docs/.nvmrc
          cp .nvmrc packages/docs/.nvmrc

      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          VERCEL_TOKEN: '${{ secrets.VERCEL_TOKEN }}'
          VERCEL_ORG_ID: '${{ secrets.VERCEL_ORG_ID }}'
          VERCEL_PROJECT_ID: '${{ secrets.DOCS_VERCEL_PROJECT_ID }}'
          WORKING_DIRECTORY: 'packages/explorer-ui'
