name: Typescript Packages

on:
  pull_request:
    paths:
      - 'packages/**'
  push:
    paths:
      - 'packages/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: 'recursive'

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvmrc

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: 'Use NodeJS by nvmrc'
        uses: actions/setup-node@v2
        with:
          node-version: '${{steps.nvmrc.outputs.NVMRC}}'

      - name: Initialize Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Node Dependencies
        run: yarn install --frozen-lockfile

      - name: Install dependencies
        run: |
          npx lerna bootstrap

      - name: Run tests # Run tests of all packages
        run: npx lerna exec npm run ci:lint
