name: Explorer UI Deploy
on:
  push:
    branches: [master]
    paths:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**'

jobs:
  deploy-explorer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy nvmrc
        run: |
          rm -rf .nvmrc
          cp .nvmrc .nvmrc

      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          VERCEL_TOKEN: '${{ secrets.VERCEL_TOKEN }}'
          VERCEL_ORG_ID: '${{ secrets.VERCEL_ORG_ID }}'
          VERCEL_PROJECT_ID: '${{ secrets.VERCEL_PROJECT_ID }}'
          WORKING_DIRECTORY: ''
